# Generated by Django 5.2 on 2026-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
