# Generated by Django 5.2.12 on 2026-03-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('rec', 'Запись'), ('master', 'Сведение'), ('instrumental', 'Аранжировка'), ('lyrics', 'Текст')], default='rec', max_length=20)),
                ('datetime', models.DateTimeField()),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('done', 'Выполнен'), ('cancelled', 'Отменен')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
